#!/usr/bin/env bash

set -e

ZIPS=(
203
207
209
211
217
219
221
223
225
227
229
231
232
237
239
249
)

for id in "${ZIPS[@]}"; do
    echo "=== $id ==="

    # Lataa alkuperäinen
    wget -q -O "${id}.orig.zip" \
        "https://tvv.fra1.digitaloceanspaces.com/${id}.zip"

    TMP=$(mktemp -d)

    unzip -q "${id}.orig.zip" -d "$TMP"

    (
        cd "$TMP"

        # Luo uusi pienennetty zip
        zip -q -9 "${OLDPWD}/${id}.zip" \
            routes.txt \
            shapes.txt \
            trips.txt
    )

    rm -rf "$TMP"
    rm -f "${id}.orig.zip"

    echo "Valmis: ${id}.zip"
done
rm -rf zips
mkdir -p zips
mv *.zip zips
