#!/usr/bin/bash
rm -rf 2*.zip
wget https://tvv.fra1.digitaloceanspaces.com/203.zip #Hameenlinna
wget https://tvv.fra1.digitaloceanspaces.com/207.zip #Joensuu
wget https://tvv.fra1.digitaloceanspaces.com/209.zip #Jyvaskyla
wget https://tvv.fra1.digitaloceanspaces.com/211.zip #Kajaani
wget https://tvv.fra1.digitaloceanspaces.com/217.zip #Kotka
wget https://tvv.fra1.digitaloceanspaces.com/219.zip #Kouvola
wget https://tvv.fra1.digitaloceanspaces.com/221.zip #Kuopio
wget https://tvv.fra1.digitaloceanspaces.com/223.zip #Lahti
wget https://tvv.fra1.digitaloceanspaces.com/225.zip #Lappeenranta
wget https://tvv.fra1.digitaloceanspaces.com/227.zip #Mikkeli
wget https://tvv.fra1.digitaloceanspaces.com/229.zip #Oulu
wget https://tvv.fra1.digitaloceanspaces.com/231.zip #Pori
wget https://tvv.fra1.digitaloceanspaces.com/232.zip #Raasepori
wget https://tvv.fra1.digitaloceanspaces.com/237.zip #Rovaniemi
wget https://tvv.fra1.digitaloceanspaces.com/239.zip #Salo
wget https://tvv.fra1.digitaloceanspaces.com/249.zip #Vaasa

